apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-python
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: auroradevacr.azurecr.io/pshah/helloworld-python:latest
          env:
            - name: TARGET
              value: "Python Sample v1"